# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-dragon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_676c605161414e3ead7a2668a55fe96c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_25579c35c5ae4a79b05821cecc8411cc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_676c605161414e3ead7a2668a55fe96c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-dragon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e91d97206aa44f8c8281df25044a6ee2 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_676c605161414e3ead7a2668a55fe96c }}/appsvc/staticsite:${{ github.sha }}'